/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedPecasRouteImport } from './routes/_authenticated/pecas'
import { Route as AuthenticatedOrdensRouteImport } from './routes/_authenticated/ordens'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedOrdensNovaRouteImport } from './routes/_authenticated/ordens.nova'
import { Route as AuthenticatedOrdensIdRouteImport } from './routes/_authenticated/ordens.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPecasRoute = AuthenticatedPecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdensRoute = AuthenticatedOrdensRouteImport.update({
  id: '/ordens',
  path: '/ordens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdensNovaRoute = AuthenticatedOrdensNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AuthenticatedOrdensRoute,
} as any)
const AuthenticatedOrdensIdRoute = AuthenticatedOrdensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOrdensRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/ordens': typeof AuthenticatedOrdensRouteWithChildren
  '/pecas': typeof AuthenticatedPecasRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/ordens/$id': typeof AuthenticatedOrdensIdRoute
  '/ordens/nova': typeof AuthenticatedOrdensNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/ordens': typeof AuthenticatedOrdensRouteWithChildren
  '/pecas': typeof AuthenticatedPecasRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/ordens/$id': typeof AuthenticatedOrdensIdRoute
  '/ordens/nova': typeof AuthenticatedOrdensNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/ordens': typeof AuthenticatedOrdensRouteWithChildren
  '/_authenticated/pecas': typeof AuthenticatedPecasRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/_authenticated/ordens/$id': typeof AuthenticatedOrdensIdRoute
  '/_authenticated/ordens/nova': typeof AuthenticatedOrdensNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/dashboard'
    | '/financeiro'
    | '/ordens'
    | '/pecas'
    | '/servicos'
    | '/ordens/$id'
    | '/ordens/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/dashboard'
    | '/financeiro'
    | '/ordens'
    | '/pecas'
    | '/servicos'
    | '/ordens/$id'
    | '/ordens/nova'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/ordens'
    | '/_authenticated/pecas'
    | '/_authenticated/servicos'
    | '/_authenticated/ordens/$id'
    | '/_authenticated/ordens/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pecas': {
      id: '/_authenticated/pecas'
      path: '/pecas'
      fullPath: '/pecas'
      preLoaderRoute: typeof AuthenticatedPecasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens': {
      id: '/_authenticated/ordens'
      path: '/ordens'
      fullPath: '/ordens'
      preLoaderRoute: typeof AuthenticatedOrdensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens/nova': {
      id: '/_authenticated/ordens/nova'
      path: '/nova'
      fullPath: '/ordens/nova'
      preLoaderRoute: typeof AuthenticatedOrdensNovaRouteImport
      parentRoute: typeof AuthenticatedOrdensRoute
    }
    '/_authenticated/ordens/$id': {
      id: '/_authenticated/ordens/$id'
      path: '/$id'
      fullPath: '/ordens/$id'
      preLoaderRoute: typeof AuthenticatedOrdensIdRouteImport
      parentRoute: typeof AuthenticatedOrdensRoute
    }
  }
}

interface AuthenticatedOrdensRouteChildren {
  AuthenticatedOrdensIdRoute: typeof AuthenticatedOrdensIdRoute
  AuthenticatedOrdensNovaRoute: typeof AuthenticatedOrdensNovaRoute
}

const AuthenticatedOrdensRouteChildren: AuthenticatedOrdensRouteChildren = {
  AuthenticatedOrdensIdRoute: AuthenticatedOrdensIdRoute,
  AuthenticatedOrdensNovaRoute: AuthenticatedOrdensNovaRoute,
}

const AuthenticatedOrdensRouteWithChildren =
  AuthenticatedOrdensRoute._addFileChildren(AuthenticatedOrdensRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedOrdensRoute: typeof AuthenticatedOrdensRouteWithChildren
  AuthenticatedPecasRoute: typeof AuthenticatedPecasRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedOrdensRoute: AuthenticatedOrdensRouteWithChildren,
  AuthenticatedPecasRoute: AuthenticatedPecasRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
